YOArtist/src/main/java/com/skypc/yoartist/vo/User.java
package com.skypc.yoartist.vo;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.Lob;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

@Entity
@Table(name = YOATables.TABLE_USER)
@DynamicUpdate(value=true)
@DynamicInsert(value=true)
public class User implements Serializable, IGenericVO {


	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;

	@Column(name = "first_name")
	private String firstName;
	
	@Column(name = "last_name")
	private String lastName;
	
	@Column(name = "password", length = 500, nullable = false)
	private String password;

	@Column(name = "email", length = 500, nullable = false, unique = true)
	private String email;
	
	@Lob
	@Column(name="profile_photo",length=100000000)
	private byte[] profilePhoto;

	@Column(name = "status")
	private String status;
	
	@Column(name = "is_deleted")
	private String isDeleted;
	
	@OneToMany(mappedBy="user",cascade=CascadeType.ALL)
	private List<UserPosts> userPosts;
	
	
	@Column(name = "email_verification_uuid")
	private String emailVerificationUUID;
	
	@OneToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "base_user")
	private BaseUser baseUser;

	/*@ManyToMany(cascade = CascadeType.ALL, fetch=FetchType.EAGER)
	@JoinTable(name = "user_roles", joinColumns = {
			@JoinColumn(name = "user_id", referencedColumnName = "id") }, inverseJoinColumns = {
					@JoinColumn(name = "role_id", referencedColumnName = "id") })
	private Set<Role> roles;*/

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date")
	private Date createdDate;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date")
	private Date modifiedDate;

	public User() {
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}
	
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	
	
	public String getIsDeleted() {
		return isDeleted;
	}

	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getEmailVerificationUUID() {
		return emailVerificationUUID;
	}

	public void setEmailVerificationUUID(String emailVerificationUUID) {
		this.emailVerificationUUID = emailVerificationUUID;
	}
	
	public byte[] getProfilePhoto() {
		return profilePhoto;
	}

	public void setProfilePhoto(byte[] profilePhoto) {
		this.profilePhoto = profilePhoto;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getModifiedDate() {
		return modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	
	
	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	
	

	public List<UserPosts> getUserPosts() {
		return userPosts;
	}

	public void setUserPosts(List<UserPosts> userPosts) {
		this.userPosts = userPosts;
	}

	public String getFullName(){
		String name="";
		if(this.firstName!=null && !this.firstName.isEmpty()){
			name+=this.firstName;
		}
		if(this.lastName!=null && !this.lastName.isEmpty()){
			name+=" "+this.lastName;
		}
		return name;
	}

	public BaseUser getBaseUser() {
		return baseUser;
	}

	public void setBaseUser(BaseUser baseUser) {
		this.baseUser = baseUser;
	}

	
}

YOArtist/src/main/webapp/WEB-INF/views/include/connectionRequestHeader.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
    <a>
    <div class="notify-dropdown" ng-controller="connection-controller as conCtrl" ng-cloak>
        <a id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="/page.html"> 
        <i title="Connection request" ng-click="conCtrl.getAllConnectionRequest()" class="fa fa-user-plus" aria-hidden="true" style="font-size: 2em !important;line-height: 0px; font-size: 20px; color: #2dc3e8;"></i> 
        <span class="badge badge-notify" style="left:-17px;">{{conCtrl.connectionCount}}</span>
        </a>
	<ul class="dropdown-menu notifications" role="menu"
		id="connectionDropdown" style="margin-top: 23px;"
		aria-labelledby="dLabel">
		<div class="notification-heading" ng-cloak="">
			<h4 class="menu-title">Connection Request</h4>
			<!-- <h4 ng-if="!conCtrl.isEmpty" class="menu-title pull-right">
				View all<i class="glyphicon glyphicon-circle-arrow-right"></i>
			</h4> -->
		</div>


		<div flex-gt-sm="100" flex>

			<md-content> <md-list flex>
			<div
				class="{{notify.notifications.length>0?'scroll-notification':''}}">
				<md-divider></md-divider>
				<md-list-item class="md-2-line hoverDiv"
					ng-repeat="con in conCtrl.connections" ng-hide="conCtrl.currentSelectedUserId==con.userId"> <a
					ng-href="${pageContext.request.contextPath}{{notification.link}}">
					<img class="img-rounded" ng-if="con.userImage"
					data-ng-src="data:image/jpeg;base64,{{con.userImage}}" alt="">
					<img class="md-avatar" ng-if="!con.userImage"
					data-ng-src="${pageContext.request.contextPath}/resources/images/profile-pic.png"
					alt="">
				</a>

				<div class="md-list-item-text" layout="column">
					<h4>
						<a ng-href="${pageContext.request.contextPath}{{con.link}}"><Strong>{{con.fullName}}</Strong></a>
						{{con.description}}
					</h4>
					<p>
						<i class="fa fa-clock-o" aria-hidden="true"></i>{{con.time}}
						<md-button class="md-raised md-primary"
							ng-click="conCtrl.acceptIgnoreConnectRequest(con.userId,true);">Connect</md-button>
						<md-button class="md-raised md-warn"
							ng-click="conCtrl.acceptIgnoreConnectRequest(con.userId,false);">Ignore</md-button>
					</p>
				</div>
				<md-divider></md-divider> </md-list-item>
			</div>
			<md-divider></md-divider> </md-list></md-content>
		</div>
		<p class="text-center" ng-if="conCtrl.isEmpty">No Connection
			request</p>

		<!-- <li class="divider"></li>
		<div class="notification-footer">
			<h4 ng-if="!conCtrl.isEmpty" class="menu-title">
				View all<i class="glyphicon glyphicon-circle-arrow-right"></i>
			</h4>
		</div> -->
	</ul>

</div></a>

YOArtist/src/main/webapp/WEB-INF/views/include/footer.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<footer class="footer">
	<div class="container">
		<p class="text-muted">Copyright &copy; Company - All rights
			reserved</p>
	</div>
	</footer>

YOArtist/src/main/webapp/WEB-INF/views/include/header.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<nav class="navbar navbar-white navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed"
				data-toggle="collapse" data-target="#navbar" aria-expanded="false"
				aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span> <span
					class="icon-bar"></span> <span class="icon-bar"></span> <span
					class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="index.html"><b>YOArtist</b></a>
		</div>
		<div id="navbar" class="navbar-collapse collapse">

			<ul class="nav navbar-nav navbar-right">
				<li>
				<script type="text/ng-template" id="autoCompleteTemplate.html">
  					<a style="cursor:pointer;"> 
						<img ng-if="match.model.image==false" class="auto-image" src="/yoartist/resources/images/profile-pic.png">
						<img ng-if="match.model.image==true" class="auto-image" src="data:image/jpeg;base64,{{match.model.userImage}}">
      					<span class="auto-name" ng-bind-html="match.model.userName | uibTypeaheadHighlight:query"></span>
  					</a>
				</script>
					<div class="form-group container-fluid typeahead-demo" ng-controller="searchBarCtrl">
						<span class="input-icon inverted">						 
						<input type="text" style="margin-left: 32px;"
						ng-model="autoSelectInput" 
						placeholder="Enter name to search" 
						uib-typeahead="userName as user.userName for user in usersForSearchBox | filter:{userName:$viewValue}" 
						typeahead-template-url="autoCompleteTemplate.html" 
						class="form-control input-sm" 
						typeahead-show-hint="true" 
						typeahead-min-length="1"
						typeahead-on-select="onSelect($item)"> 
						<i class="glyphicon glyphicon-search bg-blue"></i>
						</span>
					</div></li>
				<li><a title="Home" href="${pageContext.request.contextPath}/user/home"><i class="fa fa-home fa-2x" aria-hidden="true" style="color: #2dc3e8;"></i></a></li>
				<li><a title="Shared To Me" href="${pageContext.request.contextPath}/user/home"><i class="fa fa-share-alt fa-2x" aria-hidden="true" style="color: #2dc3e8;"></i></a></li>
				<li><a title="Connections" href="${pageContext.request.contextPath}/user/connections"><i class="fa fa-users fa-2x" aria-hidden="true" style="color: #2dc3e8;"></i></a></li>
				<li><jsp:include page="connectionRequestHeader.jsp" /></li>
				<li><jsp:include page="notificationHeader.jsp" /></li>
				<li><jsp:include page="profileHeader.jsp" /></li>
				
			</ul>
		</div>
	</div>
</nav>

YOArtist/src/main/webapp/WEB-INF/views/include/leftmenu.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<div class="col-md-3">
				<div class="profile-nav">
					<div class="widget">
						<div class="widget-body">
							<%-- <div class="user-heading round">
								<a href="#"> <img
									src='<c:url value="/resources/images/profile-pic.png"></c:url>'
									" alt="">
								</a>
								<h1>${sessionScope.SessionFullName}</h1>

							</div>
 --%>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="${pageContext.request.contextPath}/user/messages"> <i class="fa fa-envelope"></i>
										Messages <span class="label label-info pull-right r-activity"></span>
								</a></li>
								<li><a href="#"> <i class="fa fa-calendar"></i> Events
								</a></li>
							</ul>
						</div>
					</div>

					<div class="widget">
						<div class="widget-body">
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#"> <i class="fa fa-globe"></i> Pages
								</a></li>
								<li><a href="#"> <i class="fa fa-gamepad"></i> Games
								</a></li>
								<li><a href="#"> <i class="fa fa-puzzle-piece"></i> Ads
								</a></li>
								<li><a href="#"> <i class="fa fa-users"></i> Groups
								</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<!-- end left links -->
    

YOArtist/src/main/webapp/WEB-INF/views/include/notificationHeader.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<a>
<div class="notify-dropdown"
	ng-controller="notification-controller as notify" ng-cloak>
	<a id="dLabel" role="button" data-toggle="dropdown" data-target="#"
		href="/page.html"> <span class="glyphicon glyphicon-bell"
		ng-click="notify.getLimitedNotification();"
		style="font-size: 20px; line-height: 0px;color: #2dc3e8;font-size: 2em !important;"></span>
		<span class="badge badge-notify">{{notify.notificationCount}}</span>
	</a>
	<ul class="dropdown-menu notifications notifcus" role="menu"
		style="margin-top: 20px;" aria-labelledby="dLabel">
		<div class="notification-heading" ng-cloak="">
			<h4 class="menu-title">Notifications</h4>
			<h4 ng-if="!notify.isEmpty" class="menu-title pull-right">
				View all<i class="glyphicon glyphicon-circle-arrow-right"></i>
			</h4>
		</div>
		
		<div flex-gt-sm="100" flex>

			<md-content> <md-list flex>
			<div
				class="{{notify.notifications.length>0?'scroll-notification':''}}">
				<md-divider></md-divider>
				<md-list-item class="md-2-line hoverDiv"
					ng-repeat="notification in notify.notifications">
				<a ng-href="${pageContext.request.contextPath}{{notification.link}}">
					<img class="img-rounded" ng-if="notification.userImage"
					data-ng-src="data:image/jpeg;base64,{{notification.userImage}}"
					alt=""> <img class="md-avatar"
					ng-if="!notification.userImage"
					data-ng-src="${pageContext.request.contextPath}/resources/images/profile-pic.png"
					alt="">
				</a>

				<div class="md-list-item-text" layout="column">
					<h4>
						<a
							ng-href="${pageContext.request.contextPath}{{notification.link}}"><Strong style="color:#2dc3e8">{{notification.fullName}}</Strong></a>
						<span ng-bind-html="notification.description | contextPathFilter"></span>
					</h4>
					<p><i class="fa fa-clock-o" aria-hidden="true"></i> {{notification.time}}</p>
				</div>
				<md-divider></md-divider>
				</md-list-item>
			</div>
			<md-divider></md-divider> </md-list></md-content>
		</div>
		<p ng-if="notify.isEmpty" class="text-center">No records found</p>

		<div class="notification-footer">
			<h4 ng-if="!notify.isEmpty" class="menu-title">
				View all<i class="glyphicon glyphicon-circle-arrow-right"></i>
			</h4>
		</div>
	</ul>

</div></a>

YOArtist/src/main/webapp/WEB-INF/views/include/profileHeader.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%-- <li class="dropdown"><a href="#" class="dropdown-toggle"
	data-toggle="dropdown" role="button" aria-haspopup="true"
	aria-expanded="false"> Profile <span class="caret"></span>
</a>
	<ul class="dropdown-menu">
		<li><a href="profile2.html">${sessionScope.SessionFullName}</a></li>
		<li><a href="profile3.html">Account Setting</a></li>
		<li><a href="profile3.html">Privacy Setting</a></li>
		<li><a href="${pageContext.request.contextPath}/user/logout">Logout</a></li>
		<li><a href="profile4.html">Profile 4</a></li>
		<li><a href="sidebar_profile.html">Sidebar profile</a></li>
		<li><a href="user_detail.html">User detail</a></li>
		<li><a href="edit_profile.html">Edit profile</a></li>
		<li><a href="about.html">About</a></li>
		<li><a href="friends.html">Friends</a></li>
		<li><a href="friends2.html">Friends 2</a></li>
		<li><a href="profile_wall.html">Profile wall</a></li>
		<li><a href="photos1.html">Photos 1</a></li>
		<li><a href="photos2.html">Photos 2</a></li>
		<li><a href="view_photo.html">View photo</a></li>
		<li><a href="messages1.html">Messages 1</a></li>
		<li><a href="messages2.html">Messages 2</a></li>
		<li><a href="group.html">Group</a></li>
		<li><a href="list_users.html">List users</a></li>
		<li><a href="file_manager.html">File manager</a></li>
		<li><a href="people_directory.html">People directory</a></li>
		<li><a href="list_posts.html">List posts</a></li>
		<li><a href="grid_posts.html">Grid posts</a></li>
		<li><a href="forms.html">Forms</a></li>
		<li><a href="buttons.html">Buttons</a></li>
		<li><a href="error404.html">Error 404</a></li>
		<li><a href="error500.html">Error 500</a></li>
		<li><a href="recover_password.html">Recover password</a></li>
		<li><a href="registration_mail.html">Registration mail</a></li>
	</ul></li> --%>
<a>
<div class="btn-group user-profile-box">
	<a class="btn user-profile-dropdown" href="${pageContext.request.contextPath}/user/profile"><i class="fa fa-user fa-fw"></i>
		${sessionScope.SessionFullName}</a> <a class="btn dropdown-toggle" style="background: #e4dfdf;" data-toggle="dropdown"
		href="#"> <span class="fa fa-caret-down user-dropdown-icon"
		title="Toggle dropdown menu"></span>
	</a>
	<ul class="dropdown-menu">
		<li><a href="#"><i class="fa fa-user fa-fw"></i> view profile</a></li>
		<li><a href="#"><i class="fa fa-pencil fa-fw"></i> Edit profile</a></li>
		<li class="divider"></li>
		<li><a href="#"><i class="fa fa-cog"></i> account setting<br>
		<li><a href="#"><i class="fa fa-shield"></i> privacy setting<br>
		<li class="divider"></li>
		<li><a href="${pageContext.request.contextPath}/user/logout"><i class="fa fa-power-off"></i> Logout</a></li>
	</ul>
</div>
</a>

YOArtist/src/main/webapp/WEB-INF/views/include/test.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>

	<div class="notifications-wrapper"
			ng-repeat="notification in notify.notifications">
			<a class="content"
				href="${pageContext.request.contextPath}/user/notifications">
				<div class="notification-item">
					<div class="notif-image">
						<a href="${pageContext.request.contextPath}{{notification.link}}">
							<img class="img-rounded" ng-if="notification.userImage"
							data-ng-src="data:image/jpeg;base64,{{notification.userImage}}" alt=""
							>
							<img
							class="img-rounded" ng-if="!notification.userImage"
							data-ng-src="${pageContext.request.contextPath}/resources/images/profile-pic.png"
							alt="">
						</a>
						
					</div>
					<div class='notif-content'>
						<h4 class="item-title">
							<a
								style="color: #0c424a; font-size: 14px; margin-right: 2px; font-family: Verdana, Geneva, sans-serif;"
								href="${pageContext.request.contextPath}{{notification.link}}">{{notification.fullName}}</a>
							{{notification.description}}
						</h4>
						<p class="item-info">
							<i class="fa fa-clock-o" aria-hidden="true"></i>
							{{notification.time}}
							<!-- <button class="connectBtn" ng-click="notify.acceptIgnoreConnectRequest(notification.userId,true);">Connect</button>
							<button class="ignoreBtn" ng-click="notify.acceptIgnoreConnectRequest(notification.userId,false);">Ignore</button> -->
						</p>
					</div>
				</div>
			</a>

		</div>

</body>
</html>